server:
  port: 8083

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/department?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: cyq123456
  mvc:
    static-path-pattern: /**
  logging:
    level:
      root: warn
      com:
        example:
          department:
            controller: debug
            dao: debug
mybatis:
  mapper-locations: classpath:/mapper/*.xml

